BASE=../../../..
include $(BASE)/build/modmake.rules
#LIBS+=/opt/quickjs/lib/quickjs/libquickjs.lto.a
ALL_CFLAGS += -I/opt/quickjs/include/quickjs -Wno-unused-variable -Wno-unused-function -Wno-unused-but-set-variable -Wno-unused-label -Wno-declaration-after-statement -Wno-pedantic


